name: Commit Checker

on: push

jobs:
  commit-checker:
    name: Verify each commit
    runs-on: macos
    steps:
      - name: Checkout code
        uses: actions/checkout@2

      - name: Run code checker
        uses: github/super-checker@v1
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets:GITHUB_TOKEN }}
          
